# Generated by Django 6.1 on 2026-08-18 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_company', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('package_type', models.CharField(max_length=255)),
                ('sap_code', models.CharField(max_length=255)),
                ('po_number', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
                ('quantity_in_cover', models.PositiveIntegerField(help_text='Articles per box; printed on the label.', validators=[django.core.validators.MinValueValidator(1)])),
                ('issue', models.PositiveIntegerField(default=0, help_text='Total articles produced; internal only, never printed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
