# Generated by Django 6.1 on 2026-08-18 18:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_start', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sheet_end', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_events', to='labels.layout')),
            ],
            options={
                'ordering': ['-printed_at'],
            },
        ),
    ]
